### ISSUE TITLE
Broken with Gulp v4

### ISSUE THREAD

**Issue by binarykitchen** [vincentmac/gulp-fingerprint#24]
Prints this error `TypeError: file.pipe is not a function` coming from line 125 of gulp-fingerprint/index.js:125:12

**Comment by binarykitchen** [comment]
I think this commit in another fork fixes it

https://github.com/topechelon/gulp-fingerprint/commit/1400828bdb1c165144f22481a26a04dffb474eb6

Can we apply it here?

**Comment by vincentmac** [comment]
feel free to send a PR. Sorry i haven't looked at this project in a few
years

**Comment by binarykitchen** [comment]
Will do. Turns out the above PR is breaking unit tests so it's not a correct fix. 

Hmmm, it's a mess with files, streams, split, through etc ...

**Comment by binarykitchen** [comment]
Here the PR. Good changes: https://github.com/vincentmac/gulp-fingerprint/pull/25

Hope you can merge and `npm publish` that soon?
